name: DobbyVPN Build

on: [push, workflow_dispatch, workflow_call]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            os: windows-2019
            target: windows
          - arch: amd64
            os: ubuntu-20.04
            target: linux
    name: ${{ matrix.target }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties', '**/libs.versions.toml') }}

      - name: Build with Gradle
        run: |
          cd ck-client-desktop-kotlin/Client
          chmod +x ./gradlew
          ./gradlew build
          ls /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.skiko

      - if: ${{ matrix.target == 'linux' }}
        name: Conveyor build
        uses: hydraulic-software/conveyor/actions/build@v16.0
        with:
          command: make debian-package
          extra_flags: "--passphrase=\"${{ secrets.CONVEYOR_PASSPHRASE }}\" -f ck-client-desktop-kotlin/Client/conveyor.conf"
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Display file tree with sizes
        run: |
          echo "Displaying the size of files and directories in 'output' directory:"
          du -ah output | sort -rh

      # Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          draft: false
          prerelease: false

      # Upload the first package (adjust the file name as needed)
      - name: Upload Package 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/combined-vpn-client_1.0_amd64.deb
          asset_name: combined-vpn-client_1.0_amd64.deb
          asset_content_type: application/deb

      - if: ${{ matrix.target == 'windows' }}
        name: Conveyor build
        uses: hydraulic-software/conveyor/actions/build@v16.0
        with:
          command: make windows-msix
          extra_flags: "--passphrase=\"${{ secrets.CONVEYOR_PASSPHRASE }}\" -f ck-client-desktop-kotlin/Client/conveyor.conf"
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      # conveyor default cache directory is .conveyor/cache
      # Avoid caching it, causing Github space payment
      - name: Cleanup Conveyor
        if: always()
        run: |
          rm -rf .conveyor/cache/*

      - name: Display file tree with sizes
        run: |
          echo "Displaying the size of files and directories in 'output' directory:"
          du -ah output | sort -rh

      # delete output directory to free up space, Github Action only has 14G space,
      # to avoid the failure of insufficient space in the subsequent post recycling steps
      - name: Delete output directory
        run: rm -rf output
