name: Go

on:
  release:
    types: 
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          go get ./...
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev

      - name: Get linux ck-client
        run: |
          wget https://github.com/cbeuw/Cloak/releases/download/v2.9.0/ck-client-linux-amd64-v2.9.0
      - name: Linux build
        run: go build -o dobby_client -v ./...
      - name: Make linux zip
        run: |
          mkdir linux_client
          mv ck-client-linux-amd64-v2.9.0 linux_client/ck-client
          mv dobby_client linux_client/client
          zip -r linux_client.zip linux_client

      - name: Linux release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux_client.zip
          asset_name: linux_client.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Linux release"
